// Confirmed-conversion tracking for the embedded LeadConnector form and calendar.
//
// WHAT IS AND IS NOT ESTABLISHED (2026-10-08)
//
// There is no official LeadConnector documentation for these messages. The only
// public descriptions are third-party write-ups and pull requests. They agree on
// the message NAMES and disagree on the ORIGIN, and at least one reported
// payload shape conflicts with the others. LeadConnector's own help article says
// its external tracking script does not support iframe-embedded forms, so a
// postMessage listener is the only route available.
//
// So the signatures below are PLAUSIBLE BUT UNVERIFIED against this account.
// The failure mode is deliberate: a strict matcher that does not match fires
// nothing. Silence, never a false conversion. Turn on the capture mode below
// during one real submission to confirm the true shape, then tighten this.
//
// PERSONAL DATA
// One reported payload ("set-sticky-contacts") carries contact JSON including
// email, full name and phone. Nothing from any payload body is ever read into
// an event. The only field taken from a message is calendarId, which identifies
// a calendar, not a person. Everything else sent to GA4 is generated by us.

import { track, cleanPath } from "./analytics";

// Exact origins, compared whole -- never a substring or endsWith test, which
// would accept api.leadconnectorhq.com.attacker.example.
const CONVERSION_ORIGINS = [
  "https://api.leadconnectorhq.com",      // the form and calendar embeds
  "https://widgets.leadconnectorhq.com",  // the chat widget
  "https://link.msgsndr.com",
  "https://msgsndr.com",
];

const LEAD_REF_KEY = "slg-lead-ref";

/**
 * A first-party pseudonymous reference for joining GA4 to the CRM.
 *
 * Random, carries no personal data, and is generated here rather than derived
 * from anything about the visitor. It exists so that one prospect who both
 * inquires and books can be recognised as one prospect rather than two leads.
 */
export function leadRef() {
  if (typeof window === "undefined") return "";
  try {
    let v = window.localStorage.getItem(LEAD_REF_KEY);
    if (!v) {
      const b = new Uint8Array(8);
      (window.crypto || {}).getRandomValues?.(b);
      v = "slg-" + Array.from(b, (x) => x.toString(16).padStart(2, "0")).join("");
      window.localStorage.setItem(LEAD_REF_KEY, v);
    }
    return v;
  } catch {
    return ""; // storage blocked; the event still fires, just unjoinable
  }
}

// De-duplication.
//
// Deliberately NOT session-wide. A visitor who submits an inquiry, then books,
// then sends a second genuine inquiry an hour later is three real events and
// must be counted as three. This only collapses the same message arriving twice
// in quick succession, which is a transport artefact rather than a second
// prospect.
const DEDUPE_MS = 5000;
const lastSeen = new Map();
function isRepeat(key) {
  const now = Date.now();
  const prev = lastSeen.get(key);
  lastSeen.set(key, now);
  return prev !== undefined && now - prev < DEDUPE_MS;
}

/** Narrow a message to a conversion kind, or null. Strict by design. */
export function classify(data) {
  // iframe-resizer chatter is the loudest thing on this channel. Drop it first.
  if (typeof data === "string") {
    return data.indexOf("[iFrameSizer]") === 0 ? null : null;
  }
  if (Array.isArray(data)) {
    const head = data[0];
    if (head === "msgsndr-booking-complete") {
      const second = data[1];
      const calendarId =
        typeof second === "string" ? second
        : second && typeof second === "object" ? second.calendarId
        : undefined;
      return { kind: "booking", calendarId: typeof calendarId === "string" ? calendarId : undefined };
    }
    // Contact JSON rides along with this one. We read none of it.
    if (head === "set-sticky-contacts") return { kind: "inquiry" };
    return null;
  }
  if (data && typeof data === "object") {
    const t = data.type;
    if (t === "appointment" || t === "booking") return { kind: "booking", calendarId: typeof data.calendarId === "string" ? data.calendarId : undefined };
    if (t === "form") return { kind: "inquiry" };
    return null;
  }
  return null;
}

/**
 * Listen for a confirmed submission or booking from the embeds.
 *
 * Fires at most one event per confirmation:
 *   generate_lead     an inquiry the embed reported as accepted
 *   booking_complete  an appointment the embed reported as booked
 *
 * Both are conversions. Button, phone, email and chat events stay intent and
 * are not touched here.
 */
export function installConversionTracking() {
  if (typeof window === "undefined" || window.__slgConversions) return;
  window.__slgConversions = true;

  let capture = false;
  try { capture = window.localStorage.getItem("slg-embed-debug") === "1"; } catch { /* blocked */ }

  window.addEventListener("message", (e) => {
    if (!CONVERSION_ORIGINS.includes(e.origin)) return;

    if (capture) {
      // Confirmation mode. Logs locally so the true payload can be read off one
      // real submission. Never sent anywhere.
      // eslint-disable-next-line no-console
      console.log("[slg conversion probe]", e.origin, e.data);
    }

    const hit = classify(e.data);
    if (!hit) return;

    const key = `${hit.kind}:${e.origin}`;
    if (isRepeat(key)) return;

    const params = {
      lead_ref: leadRef(),
      page_path: cleanPath(typeof window !== "undefined" ? window.location.pathname : ""),
      source: hit.kind === "booking" ? "ghl_calendar" : "ghl_form",
    };
    // calendarId names a calendar, not a person.
    if (hit.kind === "booking" && hit.calendarId) params.calendar_id = hit.calendarId;

    track(hit.kind === "booking" ? "booking_complete" : "generate_lead", params);
  });
}
